export const REMOVE_CITY = 'REMOVE_CITY';
export const CLEAR_CITIES = 'CLEAR_CITIES';

export const UPDATE_CITY = 'UPDATE_CITY';
export const UPDATE_CITY_START = 'UPDATE_CITY_START';
export const UPDATE_CITY_FAIL = 'UPDATE_CITY_FAIL';

export const ADD_CITY = 'ADD_CITY';
export const ADD_CITY_START = 'ADD_CITY_START';
export const ADD_CITY_FAIL = 'ADD_CITY_FAIL';

export const FORECAST_RETRIEVE = 'FORECAST_RETRIEVE';
export const FORECAST_RETRIEVE_START = 'FORECAST_RETRIEVE_START';
export const FORECAST_RETRIEVE_FAIL = 'FORECAST_RETRIEVE_FAIL';